### ISSUE TITLE
Straight up crashed when misconfigured.

### ISSUE THREAD

**Issue by BlueDragonX** [BlueDragonX/beacon#5]
Beacon_1   | panic: config failed to parse {hostname: <nil>} as string [recovered]
Beacon_1   | 	panic: config failed to parse {hostname: <nil>} as string
Beacon_1   | 
Beacon_1   | goroutine 1 [running]:
Beacon_1   | runtime.panic(0x6a7520, 0xc210036ca0)
Beacon_1   | 	/usr/local/go/src/pkg/runtime/panic.c:266 +0xb6
Beacon_1   | gopkg.in/yaml%2ev1.handleErr(0x7f23e217aae8)
Beacon_1   | 	/usr/share/go/src/gopkg.in/yaml.v1/yaml.go:28 +0x143
Beacon_1   | runtime.panic(0x6a7520, 0xc210036ca0)
Beacon_1   | 	/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
Beacon_1   | gopkg.in/BlueDragonX/yamlcfg%2ev1.AssertIsString(0x739bb0, 0x8, 0x0, 0x0)
Beacon_1   | 	/usr/share/go/src/gopkg.in/BlueDragonX/yamlcfg.v1/errors.go:44 +0xb5
Beacon_1   | gopkg.in/BlueDragonX/yamlcfg%2ev1.GetString(0x6431e0, 0xc2100650f0, 0x739bb0, 0x8, 0x71a6a0, ...)
Beacon_1   | 	/usr/share/go/src/gopkg.in/BlueDragonX/yamlcfg.v1/parse.go:95 +0xf0
Beacon_1   | main.(*ServiceConfig).SetYAML(0xc210059420, 0x727aa0, 0x7, 0x6431e0, 0xc2100650f0, ...)
Beacon_1   | 	/tmp/build/src/beacon/config.go:104 +0x198
Beacon_1   | main.(*Config).SetYAML(0xc210059410, 0xc210000360, 0x5, 0x6431e0, 0xc210065060, ...)
Beacon_1   | 	/tmp/build/src/beacon/config.go:210 +0x24b
Beacon_1   | gopkg.in/yaml%2ev1.func·001()
Beacon_1   | 	/usr/share/go/src/gopkg.in/yaml.v1/decode.go:221 +0x83
Beacon_1   | gopkg.in/yaml%2ev1.(*decoder).mapping(0x7f23e217aa90, 0xc21004a240, 0x6ed020, 0xc210059410, 0x196, ...)
Beacon_1   | 	/usr/share/go/src/gopkg.in/yaml.v1/decode.go:503 +0x11a
Beacon_1   | gopkg.in/yaml%2ev1.(*decoder).unmarshal(0x7f23e217aa90, 0xc21004a240, 0x6ed020, 0xc210059410, 0x196, ...)
Beacon_1   | 	/usr/share/go/src/gopkg.in/yaml.v1/decode.go:261 +0x99
Beacon_1   | gopkg.in/yaml%2ev1.(*decoder).document(0x7f23e217aa90, 0xc21004a1e0, 0x6ed020, 0xc210059410, 0x196, ...)
Beacon_1   | 	/usr/share/go/src/gopkg.in/yaml.v1/decode.go:273 +0x77
Beacon_1   | gopkg.in/yaml%2ev1.(*decoder).unmarshal(0x7f23e217aa90, 0xc21004a1e0, 0x6ed020, 0xc210059410, 0x196, ...)
Beacon_1   | 	/usr/share/go/src/gopkg.in/yaml.v1/decode.go:255 +0x67
Beacon_1   | gopkg.in/yaml%2ev1.Unmarshal(0xc21000ba00, 0x69, 0x269, 0x6c4900, 0xc210059410, ...)
Beacon_1   | 	/usr/share/go/src/gopkg.in/yaml.v1/yaml.go:95 +0x205
Beacon_1   | main.LoadConfig(0x2, 0x722a60, 0x6, 0xc21000ae70, 0x0, ...)
Beacon_1   | 	/tmp/build/src/beacon/config.go:287 +0x226
Beacon_1   | main.main()
Beacon_1   | 	/tmp/build/src/beacon/main.go:23 +0x1d4
Beacon_1   | 
Beacon_1   | goroutine 3 [runnable]:
Beacon_1   | os/signal.loop()
Beacon_1   | 	/usr/local/go/src/pkg/os/signal/signal_unix.go:19
Beacon_1   | created by os/signal.init·1
Beacon_1   | 	/usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x31

**Comment by BlueDragonX** [comment]
Should be fixed in v2 branch.
